Split Plot class into interface and UI
Plot - has all function definitions
PlotBase - simply uses .ui to setup it's contents

Can't do it in one file - causes circular import:
ImportError: cannot import name 'Plot' from partially initialized module 'gui.views.plots' (most likely due to a circular import)